function [data] = Masteractinthresh(dir0,dir1,source_filename,p)
% This function takes an input image sequence and a thersholding
% percentile, p, and computes the actin filtered image by using the
% thresholded diaphanous signal as a mask.
%Example: data = Masteractinthresh(dir0,dir1,source_filename,p)
% The output structure, data, includes image stacks with gaussian filtered
% images(.filtered), the masked actin data (.actinmasked), as well as some
% other files. The input dir1 is the parent folder of the image sequence,
% dir0 is the parent folder of that folder, source_filename is a root of
% the filename, and p is the thresholding percentile.
%% 
% This is a script that uses the diaphanous IHC signal to process the actin
% signal generated by injecting fluorescently labeled actin monomers. The
% strategy is to threshold diaphanous at different level, generate a mask,
% and then exclude actin signal that falls outside of this mask.
%{ 
%% User Inputs
dir0 = '/Users/Jonathan/Desktop/'
dir1 = '/Users/Jonathan/Desktop/Image1_032315/' %where the files are starting
source_filename = 'Image1_032315'
p = 98 %thresholding percentile
%}

%% Loading images
[actin,dia,sqh,zdepth] = loadfixedimage(dir1,source_filename);
disp('Loading Images...')
%gaussian filtering
for i = 1:zdepth
    data.filtered_actin(:,:,i) = gaussfilt(actin(:,:,i),0.7);
    data.filtered_dia(:,:,i) = gaussfilt(dia(:,:,i),0.7);
    data.filtered_sqh(:,:,i) = gaussfilt(sqh(:,:,i),0.7);
end

%% thresholding
[rowdim,coldim] = size(dia(:,:,1));
diathresh = zeros(rowdim,coldim,zdepth);
level = prctilethresh(dia(:,:,:),p) ;
disp('Thresholding...')
for i = 1:zdepth
    bright_ind = find(dia(:,:,i)>=level);
    imbw = zeros(rowdim,coldim);
    imbw(bright_ind) = 1;
    data.diathresh(:,:,i) = imbw;
    clear imbw
end

%% Mask subtraction

data.actinmasked = uint8(double(data.filtered_actin).*data.diathresh);

%% File saving
disp('Saving Files...')
mkdir(dir0,strcat(source_filename,'_dia_threshold',num2str(p)));
mkdir(dir0,strcat(source_filename,'_actinmasked_threshold',num2str(p)))
dirdia = strcat(dir0,'/',source_filename,'_dia_threshold',num2str(p),'/');
diract = strcat(dir0,'/',source_filename,'_actinmasked_threshold',num2str(p),'/');
diathresh_filename = strcat('diathresh_',num2str(p));
actinmasked_filename = strcat('actinmasked_',num2str(p));
for i = 1:zdepth
    imwrite(data.diathresh(:,:,i),    [dirdia,diathresh_filename,  '_z',sprintf('%03d',i),'_c001.tif'],'tif','Compression','none')
    imwrite(data.actinmasked(:,:,i),  [diract,actinmasked_filename,'_z',sprintf('%03d',i),'_c002.tif'],'tif','Compression','none')
end
disp('Done')


%{
%% Image display Testing
figure
subplot(2,3,1), imagesc(diathresh(:,:,20))
subplot(2,3,2), imagesc(diathresh(:,:,10))
subplot(2,3,3), imagesc(diathresh(:,:,2))
subplot(2,3,4), imagesc(diathresh(:,:,4))
subplot(2,3,5), imagesc(diathresh(:,:,6))

figure
subplot(2,1,1), imagesc(actin(:,:,20))
subplot(2,1,2), imagesc(actinmasked(:,:,20))

%}
